name: divya_drishti
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Update these packages:
  permission_handler: ^11.0.0  # Updated from ^10.4.4
  url_launcher: ^6.1.12
  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  device_info_plus: ^10.1.2
  sensors_plus: ^5.0.1
  provider: ^6.0.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^32.1.22
  flutter_dotenv: ^5.1.0
 
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.0.5


  flutter_localizations:
    sdk: flutter
 
  # Other dependencies
  http: ^1.1.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0  
  location: ^5.0.3
  flutter_foreground_task: ^6.0.0
  crypto: ^3.0.5
  youtube_player_flutter: ^9.1.3
 
  image_picker: ^1.0.4
  webview_flutter: ^4.4.2
   
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg